package com.capgemini.dao;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;



import com.capgemini.dto.DiagnosticCenter;
import com.capgemini.dto.Appointment;
import com.capgemini.dto.Test;
import com.capgemini.util.*;
import com.capgemini.service.*;

@SuppressWarnings("unused")
public class HealthCareDaoImpl implements HealthCareDao {
	//private Logger logger=Logger.getLogger(HealthCareDao.class);
	DiagnosticCenter centerObj;
	
	Test testObj;
	
	public boolean addCenter(DiagnosticCenter center) {
		List<Test> defaultTests = new ArrayList<Test>(); //adding 3 default tests to the Test arrayList of the newly added center.
		defaultTests.add(new Test(HealthCareDataBase.testAutogeneratedId(),"blood group"));
		defaultTests.add(new Test(HealthCareDataBase.testAutogeneratedId(),"blood sugar"));
		defaultTests.add(new Test(HealthCareDataBase.testAutogeneratedId(),"blood pressure"));
		
		center.setListOfTests(defaultTests);
		return HealthCareDataBase.centerList.add(center); //this will return true if added to the center arrayList.
	}
	public boolean addAppointment(Appointment appointment){
		return HealthCareDataBase.AppointmentList.add(appointment);	
	}
	
	public boolean makeAppointment(BigInteger appointmentid, DiagnosticCenter center, Test test, String date, boolean approved)
	{
		Appointment appointment = new Appointment(appointmentid, center,test,date,approved);
		addAppointment(appointment);
		//System.out.println(appointment);
		return true;
	}
	
	public void viewAppointments(){
		System.out.println("Appointment Id"+" "+"Date"+" "+"Center"+" "+"Test"+" "+"Approval");
		for(Appointment ap:HealthCareDataBase.AppointmentList)
		{
			System.out.println(ap.getAppointmentid()+""+ap.getDate()+""+ap.getCenterid()+""+ap.getTestid()+""+ap.isApproved());
		}
	}
	
	public boolean removeCenter(DiagnosticCenter center) { //this method is interacting with the DiagnosticCenter arrayList if the centerObject mathces with the passed centerObject than it is removing the center.
		Iterator<DiagnosticCenter> itr = HealthCareDataBase.centerList.iterator();
		while(itr.hasNext())
		{
			DiagnosticCenter c = itr.next();
			if(c==center)
			{
				itr.remove();
			}
		}
		return true;	
	}
	
	public String addTest(DiagnosticCenter center,Test test) {
		center.getListOfTests().add(test);
		return "Test Added successfully";
	}
	
	public boolean removeTest(DiagnosticCenter center,Test test) { 
		Iterator<Test> itr = center.getListOfTests().iterator();
		while(itr.hasNext())
		{
			Test t = itr.next();
			if(t==test)
			{
				itr.remove();
			}
		}
		return true;
	}
	
	public void viewCenters()
	{
		System.out.println("Center Id"+"        "+"Center Name");
		for(DiagnosticCenter dc:HealthCareDataBase.centerList)
		{
			System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
		}
	}
	
	
	
	public void viewCentersAndTests()
	{
		for(DiagnosticCenter dc:HealthCareDataBase.centerList)
		{
			System.out.println();
			System.out.println("Center Id"+"        "+"Center Name");
			System.out.println(dc.getCenterId()+"               "+dc.getCenterName());
			System.out.println();
			System.out.println("Tests under "+dc.getCenterName()+" are:");
			System.out.println("Test Id"+"          "+"Test Name");
			for(Test t:dc.getListOfTests())
			{
				System.out.println(t.getTestId()+"               "+t.getTestName());
			}
		}
	}
	
	public void viewCenterRepectiveTests(String centerId)
	{
		DiagnosticCenter center = getCenterObjectOfcenterId(centerId);
		System.out.println("Tests under "+center.getCenterName()+" are:");
		System.out.println("Test Id"+"          "+"Test Name");
		for(Test t:center.getListOfTests())
		{	
			System.out.println(t.getTestId()+"               "+t.getTestName());	
		}
	}
	
	public DiagnosticCenter getCenterObjectOfcenterId(String centerId) //this method interacts with DiagnosticCenter arrayList and returns the centerObject corressponding to the given CenterId.
	{
		Iterator<DiagnosticCenter> itr = HealthCareDataBase.centerList.iterator();
		while(itr.hasNext())
		{
			DiagnosticCenter c = itr.next();
			if(c.getCenterId().equals(centerId))
			{
				centerObj=c;
			}
		}
		return centerObj;
	}
	
	public boolean isCenterNamePresent(String centerName) //this method interacts with DiagnosticCenter arrayList and returns the centerObject corressponding to the given CenterId.
	{
		DiagnosticCenter centerObject=null;
		Iterator<DiagnosticCenter> itr = HealthCareDataBase.centerList.iterator();
		while(itr.hasNext())
		{
			DiagnosticCenter c = itr.next();
			if(c.getCenterName().equals(centerName))
			{
				centerObject=c;
			}
		}
		if(centerObject==null)
		{
			return false;
		}
		return true;
	}
	
	public boolean isCenterIdPresent(String centerId) //this method interacts with DiagnosticCenter arrayList and returns the centerObject corressponding to the given CenterId.
	{
		DiagnosticCenter centerObject=null;
		Iterator<DiagnosticCenter> itr = HealthCareDataBase.centerList.iterator();
		while(itr.hasNext())
		{
			DiagnosticCenter c = itr.next();
			if(c.getCenterId().equals(centerId))
			{
				centerObject=c;
			}
		}
		if(centerObject==null)
		{
			return false;
		}
		return true;
	}
	
	public Test getTestObject(DiagnosticCenter center, String testId)
	{
		Iterator<Test> itr = center.getListOfTests().iterator();
		while(itr.hasNext())
		{
			Test t = itr.next();
			if(t.getTestId().equals(testId))
			{
				testObj = t;
			}
		}
		return testObj;
	}
	
	public boolean isTestNamePresent(DiagnosticCenter centerObject,String testName)
	{
		Test testObject=null;
		Iterator<Test> itr = centerObject.getListOfTests().iterator();
		while(itr.hasNext())
		{
			Test t = itr.next();
			if(t.getTestName().equals(testName))
			{
				testObject=t;
			}
		}
		if(testObject==null)
		{
			return false;
		}
		return true;
	}
	
	public boolean isTestIdPresent(DiagnosticCenter centerObject,String testId)
	{
		Test testObject=null;
		Iterator<Test> itr = centerObject.getListOfTests().iterator();
		while(itr.hasNext())
		{
			Test t = itr.next();
			if(t.getTestId().equals(testId))
			{
				testObject=t;
			}
		}
		if(testObject==null)
		{
			return false;
		}
		return true;
	}
	
	
}
